name: Build Base
on: workflow_dispatch

jobs:
  build-amd64:
    name: Build AMD64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Build
        run: |
          make base-amd64
          make base-tar-amd64

      - name: Upload image to artifact
        uses: actions/upload-artifact@v3
        with:
          name: image-amd64
          path: image-amd64.tar

  build-arm64:
    name: Build ARM64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Build
        run: |
          make base-arm64 || make base-arm64
          make base-tar-arm64

      - name: Upload image to artifact
        uses: actions/upload-artifact@v3
        with:
          name: image-arm64
          path: image-arm64.tar

  push:
    needs:
      - build-amd64
    name: push
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Download image
        uses: actions/download-artifact@v3
        with:
          name: image-amd64


      - name: Load Image
        run: |
          docker load --input image-amd64.tar
 

      - name: Push
        run: |
          cat VERSION
          TAG=$(cat VERSION)
          docker login -u inspurwyd  -p  dckr_pat_yMRt21vCZj0PlDl14xJiqSOHeVg
          
          docker tag kubeovn/kube-ovn-base:$TAG-amd64 inspurwyd/kube-ovn-base:$TAG-amd64
          docker images
          docker push inspurwyd/kube-ovn-base:$TAG-amd64
