name: Build arm64 Image
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
  push:
    branches:
    - master
    - release-*
    paths-ignore:
    - 'docs/**'
    - '**.md'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  GO_VERSION: ''

jobs:
  build:
    name: Build arm64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION || '' }}
          go-version-file: go.mod
          check-latest: true
          cache: false

      - name: Export Go full version
        run: echo "GO_FULL_VER=$(go version | awk '{print $3}')" >> "$GITHUB_ENV"

      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-${{ env.GO_FULL_VER }}-arm64-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-${{ env.GO_FULL_VER }}-arm64-

      - name: Build
        run: make release-arm || make release-arm

      - name: Push
        run: |
          TAG=$(cat VERSION) 
          docker login -u inspurwyd  -p  dckr_pat_yMRt21vCZj0PlDl14xJiqSOHeVg
          docker tag kubeovn/kube-ovn:$TAG inspurwyd/kube-ovn:$TAG-arm
          docker tag kubeovn/kube-ovn:$TAG-debug inspurwyd/kube-ovn:$TAG-debug-arm
          docker images
          docker push inspurwyd/kube-ovn:$TAG-arm
          docker push inspurwyd/kube-ovn:$TAG-debug-arm
